### ISSUE TITLE
Support video texture

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-globe#10]
**Is your feature request related to a problem? Please describe.**
My project requires very complex dynamic effects on the globe surface, it's hard to code in three.js, but we cloud make a 2:1 globe video to simulate all effects. 
Three.js has a video texture [demo](https://threejs.org/examples/?q=video#webgl_materials_video), so is there possible to render video texture on the globe?

**Describe the solution you'd like**
Like the  [demo](https://threejs.org/examples/?q=video#webgl_materials_video), we cloud customize a video texture in globeMaterial()

In addition, like #9, support image/video content on the globe with particular location would be a nice feature

**Comment by vasturiano** [comment]
@lslzl3000 thanks for reaching out.

That's an interesting request. Is this something you could potentially achieve by manipulating the globe wrapping material, accessible via `.globeMaterial()`?

Alternatively you could create a custom layer that renders another sphere (or fraction of a sphere) with a video texture on.

Globe material example:
https://github.com/vasturiano/three-globe/blob/master/example/custom-material/index.html#L23-L27

Custom layer example:
https://github.com/vasturiano/three-globe/blob/master/example/custom/index.html#L24-L34

**Comment by lslzl3000** [comment]
Thanks for your reply. I've successfully created surface image/video labels in the custom layer. So I'll close this issue

**Comment by vasturiano** [comment]
@lslzl3000 nice! Do you have a demo you could share? 😃

**Comment by lslzl3000** [comment]
@vasturiano here is a simple demo, could add image/video with given lat/lng and given size.

```
// create a blank sphere with given w&h, then rotate to (lat, lng)
function addSurfacePanel(lat, lng, alt, width, height) {
	let R = 100 + alt// globe raduis
	let geometry = new THREE.SphereBufferGeometry(R, 160, 160, Math.PI / 180 * (90 - width / 2 + lng), Math.PI / 180 * width, Math.PI / 180 * (90 - height / 2), Math.PI / 180 * height)
	let material = new THREE.MeshBasicMaterial()
	let sphere = new THREE.Mesh(geometry, material)

	sphere.rotation.x = Math.PI / 180 * lat * Math.cos(Math.PI / 180 * lng)
	sphere.rotation.z = Math.PI / 180 * lat * -Math.sin(Math.PI / 180 * lng)

	return sphere
}

// load texture
function loadTexture(url, onProgress) {
	return new Promise((resolve, reject) => {
		new THREE.TextureLoader().load(url, resolve, onProgress, reject)
	})
}

// e.g. load a image at (0,0), a video at(0,180)
const customLayerData = [
	{ type: 'image', id: 't1', lat: 0, lng: 0, alt:0.1, width: 60, height: 40, url: '/image/earth-day.jpg' },
	{ type: 'video', id: 't2', lat: 0, lng: 180,  alt:0.1, width: 60, height: 40, url: '/video/demo.mp4', autoplay: false }
]

globe.customLayerData(customLayerData)
	.customThreeObject(d => {
		switch (d.type) {
			case 'image':
				return addSurfacePanel(d.lat, d.lng, d.alt, d.width, d.height)
				break
			case 'video':
				// for video, create a video element first
				let video = document.createElement('video')
				video.id = d.id
				video.src = d.url
				video.style.display = 'none'
				document.body.appendChild(video)
				// this will be easier when use Vue/React/.. to manage dom

				return addSurfacePanel(d.lat, d.lng,  d.alt, d.width, d.height)
				break
			// other types
		}
	}).customThreeObjectUpdate(async (obj, d) => {
		let texture
		switch (d.type) {
			case 'image':
				texture = await loadTexture(d.url)
				obj.material.map = texture
				obj.material.needsUpdate = true
				break
			case 'video':
				let video = document.querySelector('video#'+d.id) // could access easily in Vue/React...
				if (d.autoplay)
					video.play()
				else
					video.currentTime = 1

				// replace texture with videoTexture
				texture = new THREE.VideoTexture(video)
				texture.minFilter = THREE.LinearFilter
				texture.magFilter = THREE.LinearFilter
				texture.format = THREE.RGBFormat
				obj.material.map = texture
				obj.material.needsUpdate = true
				break
		}
	}).onCustomLayerClick(obj => {
		if (obj.type == 'video') {
			let video = document.querySelector('video#'+d.id) // could access easily in Vue/React...
			video.paused ? video.play() : video.pause()
		}
	})
```
Static image
![Screen Shot 2020-07-16 at 20 01 07](https://user-images.githubusercontent.com/3398981/87668706-2a340080-c79f-11ea-8de1-a2925c5db938.png)

Live video play
![Screen Shot 2020-07-16 at 20 01 25](https://user-images.githubusercontent.com/3398981/87668710-2c965a80-c79f-11ea-81b3-c4aa625c4860.png)

**Comment by bumbeishvili** [comment]
The video layer is potentially very useful.

It can be used to visualize different kinds of animated data from 

http://nomads.ncep.noaa.gov

Here is a water vapor example (it uses video overlay but on top of a 2d map)

https://user-images.githubusercontent.com/6873202/152752302-339eb1d7-5e7a-479f-a621-58c500803b6d.mp4

**Comment by vasturiano** [comment]
@bumbeishvili thanks for your pointer.

Also worth noting that this can now more easily be achieved with the [tiles layer](https://vasturiano.github.io/three-globe/example/tiles/). See docs here: https://github.com/vasturiano/three-globe#tiles-layer

Essentially each custom positioned tile can be setup with its own `tileMaterial` which can be linked to a video, using Three's [VideoTexture](https://threejs.org/docs/#api/en/textures/VideoTexture).

Alternatively the same thing could potentially be achieved in the same manner as the [clouds example](https://globe.gl/example/clouds/), by extending the existing scene with a globe wide object showing the water vapor. That is even a more flexible approach for some custom use cases. You can see the relevant code here:
https://github.com/vasturiano/globe.gl/blob/3e3140fdf9595439d15ebbd3a198948dd071af59/example/clouds/index.html#L29-L40
