### ISSUE TITLE
On iphone Safari 18.2, three-globe examples recently stopped rendering the polygons and other features, but only show the globe.

### ISSUE THREAD

**Issue by jw997** [vasturiano/three-globe#100]
**Describe the bug**
On iphone and ipad safari 18.2 and 18.1.1 the three-globe examples show only the globe and surface, and not any of the animated polygons or other features

**To Reproduce**
1. Go to ipad or iphone safari
2. open any three-globe example for example https://vasturiano.github.io/three-globe/example/basic/
3. see the globe render, but no country polygons
4. the globe without the expected colored spikes from the pointsData

**Expected behavior**
Globe should display along with red, blue white and green spikes.

**Screenshots**
Attached screen shot showing globe without colorful spikes from points data.

**Desktop (please complete the following information):**
 - OS: ios or ipad os
 - Browser safari
 - Version 18.1.1 and 18.2

**Smartphone (please complete the following information):**

**Additional context**
First noticed on 18.1.1 on Dec 16.  Also reproduced on 18.2.  Happens on the ipads and iphones in the Apple store, too.
I think everything worked fine last week! 

![threeglobeiosbug](https://github.com/user-attachments/assets/559ad1e2-f926-49b8-ab12-8c6358c49eba)

**Comment by vasturiano** [comment]
Thanks @jw997. This should now be fixed in the latest version.
