### ISSUE TITLE
Polygon Layer cannot cover globe surface with small altitude value, holes in big regions

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-globe#11]
**Describe the bug**
The polygon geometries cannot cover the globe surface if set with a small altitude value. 

set 0 altitude, make polygon layer close to the surface, it only shows borders for most of countries
![Screen Shot 2020-07-15 at 20 18 06](https://user-images.githubusercontent.com/3398981/87546857-d06b0200-c6dc-11ea-979c-1bc4e44037d6.jpg)

with bigger altitude value, more regions show, but still leaves holes in big countries, like China, Russia
![Screen Shot 2020-07-15 at 20 18 48](https://user-images.githubusercontent.com/3398981/87547069-23dd5000-c6dd-11ea-84c5-7591e96c1198.jpg)

It seems that the ConicPolygonBufferGeometry with border coords is not fully fit the curve of a globe.

**Expected behavior**
It should cover all surface event with 0 altitude.

**Comment by lslzl3000** [comment]
Any ideas to fix this problem? A large altitude value is not a solution, the polygon layer should press/close to the surface

**Comment by lslzl3000** [comment]
Any ideas to fix this problem? A large altitude value is not a solution, the polygon layer should press/close to the surface.
Any improvements on ConicPolygonBufferGeometry  or three-conic-polygon-geometry?

**Comment by vasturiano** [comment]
@lslzl3000 this is a difficult problem to solve. Because it's not really possible to make a spherical surface that is 100% curved, it's always an approximation with face polygons.
I think the way forward is to add a feature to https://github.com/vasturiano/three-conic-polygon-geometry that allows the specification of the spheric resolution. The triangulation of the surface points will be a bit of a complicated operation though.

Could you log an issue on that repo?

**Comment by lslzl3000** [comment]
@vasturiano I think text geometry has the same problem, or feature to be added. it will be a great feature if text labels could curved nicely around the surface, especially for long text labels

I try to prevent long text like this:
![Screen Shot 2020-07-16 at 05 29 48](https://user-images.githubusercontent.com/3398981/87600192-6a0ad180-c726-11ea-95d6-60b839ecee0e.png)

I hacked your label.js with an unofficial Three.BendModifier(found some where online):
`
THREE.BendModifier = function() {};

THREE.BendModifier.prototype = {
	constructor: THREE.BendModifier,
	set: function(direction, axis, angle) {
		this.direction = new THREE.Vector3();
		this.direction.copy(direction);
		this.axis = new THREE.Vector3();
		this.axis.copy(axis);
		this.angle = angle;
		return this
	},
	_sign: function(a) {
		return 0 > a ? -1 : 0 < a ? 1 : 0
	},
	_cosh: function(x) {
		return (Math.exp(x) + Math.exp(-x)) / 2;
	},
	_sinhInverse: function(x) {
		return Math.log(Math.abs(x) + Math.sqrt(x * x + 1));
	},
	modify: function(geometry) {
		var thirdAxis = new THREE.Vector3();
		thirdAxis.crossVectors(this.direction, this.axis);

		// P - matrices of the change-of-coordinates
		var P = new THREE.Matrix4();
		P.set(thirdAxis.x, thirdAxis.y, thirdAxis.z, 0,
			this.direction.x, this.direction.y, this.direction.z, 0,
			this.axis.x, this.axis.y, this.axis.z, 0,
			0, 0, 0, 1).transpose();

		var InverseP = new THREE.Matrix4().getInverse(P);
		var newVertices = [];
		var oldVertices = [];
		var anglesBetweenOldandNewVertices = [];

		var meshGeometryBoundingBoxMaxx = 0;
		var meshGeometryBoundingBoxMinx = 0;
		var meshGeometryBoundingBoxMaxy = 0;
		var meshGeometryBoundingBoxMiny = 0;

		for (var i = 0; i < geometry.vertices.length; i++) {

			newVertices[i] = new THREE.Vector3();
			newVertices[i].copy(geometry.vertices[i]).applyMatrix4(InverseP);
			if (newVertices[i].x > meshGeometryBoundingBoxMaxx) { meshGeometryBoundingBoxMaxx = newVertices[i].x; }
			if (newVertices[i].x < meshGeometryBoundingBoxMinx) { meshGeometryBoundingBoxMinx = newVertices[i].x; }
			if (newVertices[i].y > meshGeometryBoundingBoxMaxy) { meshGeometryBoundingBoxMaxy = newVertices[i].y; }
			if (newVertices[i].y < meshGeometryBoundingBoxMiny) { meshGeometryBoundingBoxMiny = newVertices[i].y; }

		}

		var meshWidthold = meshGeometryBoundingBoxMaxx - meshGeometryBoundingBoxMinx;
		var meshDepth = meshGeometryBoundingBoxMaxy - meshGeometryBoundingBoxMiny;
		var ParamB = 2 * this._sinhInverse(Math.tan(this.angle)) / meshWidthold;
		var oldMiddlex = (meshGeometryBoundingBoxMaxx + meshGeometryBoundingBoxMinx) / 2;
		var oldMiddley = (meshGeometryBoundingBoxMaxy + meshGeometryBoundingBoxMiny) / 2;

		for (var i = 0; i < geometry.vertices.length; i++) {

			oldVertices[i] = new THREE.Vector3();
			oldVertices[i].copy(newVertices[i]);
			newVertices[i].x = this._sign(newVertices[i].x - oldMiddlex) * 1 / ParamB * this._sinhInverse((newVertices[i].x - oldMiddlex) * ParamB);

		}

		var meshWidth = 2 / ParamB * this._sinhInverse(meshWidthold / 2 * ParamB);

		var NewParamB = 2 * this._sinhInverse(Math.tan(this.angle)) / meshWidth;

		var rightEdgePos = new THREE.Vector3(meshWidth / 2, -meshDepth / 2, 0);
		rightEdgePos.y = 1 / NewParamB * this._cosh(NewParamB * rightEdgePos.x) - 1 / NewParamB - meshDepth / 2;

		var bendCenter = new THREE.Vector3(0, rightEdgePos.y + rightEdgePos.x / Math.tan(this.angle), 0);

		for (var i = 0; i < geometry.vertices.length; i++) {

			var x0 = this._sign(oldVertices[i].x - oldMiddlex) * 1 / ParamB * this._sinhInverse((oldVertices[i].x - oldMiddlex) * ParamB);
			var y0 = 1 / NewParamB * this._cosh(NewParamB * x0) - 1 / NewParamB;

			var k = new THREE.Vector3(bendCenter.x - x0, bendCenter.y - (y0 - meshDepth / 2), bendCenter.z).normalize();

			var Q = new THREE.Vector3();
			Q.addVectors(new THREE.Vector3(x0, y0 - meshDepth / 2, oldVertices[i].z), k.multiplyScalar(oldVertices[i].y + meshDepth / 2));
			newVertices[i].x = Q.x;
			newVertices[i].y = Q.y;

		}

		var middle = oldMiddlex * meshWidth / meshWidthold;

		for (var i = 0; i < geometry.vertices.length; i++) {

			var O = new THREE.Vector3(oldMiddlex, oldMiddley, oldVertices[i].z);
			var p = new THREE.Vector3();
			p.subVectors(oldVertices[i], O);
			var q = new THREE.Vector3();
			q.subVectors(newVertices[i], O);

			anglesBetweenOldandNewVertices[i] = Math.acos(1 / this._cosh(ParamB * newVertices[i].x)) * this._sign(newVertices[i].x);

			newVertices[i].x = newVertices[i].x + middle;
			geometry.vertices[i].copy(newVertices[i].applyMatrix4(P));

		}

		geometry.computeFaceNormals();
		geometry.verticesNeedUpdate = true;
		geometry.normalsNeedUpdate = true;

		// compute Vertex Normals
		var fvNames = ['a', 'b', 'c', 'd'];

		for (var f = 0, fl = geometry.faces.length; f < fl; f++) {

			var face = geometry.faces[f];
			if (face.vertexNormals === undefined) {
				continue;
			}
			for (var v = 0, vl = face.vertexNormals.length; v < vl; v++) {

				var angle = anglesBetweenOldandNewVertices[face[fvNames[v]]];
				var x = this.axis.x;
				var y = this.axis.y;
				var z = this.axis.z;

				var rotateMatrix = new THREE.Matrix3();
				rotateMatrix.set(Math.cos(angle) + (1 - Math.cos(angle)) * x * x, (1 - Math.cos(angle)) * x * y - Math.sin(angle) * z, (1 - Math.cos(angle)) * x * z + Math.sin(angle) * y,
					(1 - Math.cos(angle)) * y * x + Math.sin(angle) * z, Math.cos(angle) + (1 - Math.cos(angle)) * y * y, (1 - Math.cos(angle)) * y * z - Math.sin(angle) * x,
					(1 - Math.cos(angle)) * z * x - Math.sin(angle) * y, (1 - Math.cos(angle)) * z * y + Math.sin(angle) * x, Math.cos(angle) + (1 - Math.cos(angle)) * z * z);

				face.vertexNormals[v].applyMatrix3(rotateMatrix);

			}

		}
		// end compute Vertex Normals			
		return this
	}
}
`

And then bend the text geometry around the globe:

`
textObj.geometry = new TextGeometry(textAccessor(d), {
	font: state.font,
	size: textHeight,
	height: 0,
	curveSegments: state.labelResolution
}); // center text (otherwise anchor is on bottom-left)
dotOrient !== 'right' && textObj.geometry.center();

var modifier = new THREE.BendModifier();
var width = textObj.geometry.boundingBox.max.x - textObj.geometry.boundingBox.min.x
var dir = new THREE.Vector3(0, 0, -1);
var ax = new THREE.Vector3(0, 1, 0);
var ang = 0.0046 * width;
modifier.set(dir, ax, ang).modify(textObj.geometry);
`

It works fine for all labels with any size:
![Screen Shot 2020-07-16 at 05 29 13](https://user-images.githubusercontent.com/3398981/87601702-316bf780-c728-11ea-94e5-3fa09161c248.png)

So, we may dig the code some day, and achieve the feature with buffered geometry with more efficient way.
Also for polygon layer, can we also apply this kind of method to bend polygon around the globe?
