### ISSUE TITLE
support rendering loading icon until globe is ready

### ISSUE THREAD

**Issue by edwmurph** [vasturiano/three-globe#15]
**Is your feature request related to a problem? Please describe.**
It'd be a better user experience if a customizable loading icon could be rendered until the globe is ready and rendered like:

https://jsfiddle.net/vfug1adn/19/

**Describe the solution you'd like**
A fine minimal solution would be to allow users to provide a callback that is run at the start of [`initGlobe`](https://github.com/vasturiano/three-globe/blob/f03958efb1919315afcc7776e2c2670e62bed54d/src/globe-kapsule.js#L231-L248). In my case the callback would be used to remove the loading icon from the screen now that the globe is ready

**Describe alternatives you've considered**
I guess the "threejs" way of doing this might also be to use the [LoadingManager](https://threejs.org/docs/#api/en/loaders/managers/LoadingManager) somehow

**Additional context**

**Comment by vasturiano** [comment]
@edwmurph thanks for reaching out.

A callback method `onGlobeReady` has been added to the api for this purpose.

**Comment by edwmurph** [comment]
confirmed this worked perfectly for my use case thanks!
