### ISSUE TITLE
[Bug?]Wrong shortest line between two standard GPS coords in path

### ISSUE THREAD

**Issue by lslzl3000** [vasturiano/three-globe#20]
**Describe the bug**
If using standard GPS coords[-90/90, 180/180], for those lines pass through 180/-180
e.g. between [116, 30] and [-175, 30], 

![1610552897925](https://user-images.githubusercontent.com/3398981/104475325-ec068500-55f9-11eb-81fa-4d7a337b1864.jpg)
 the shortest way should pass 180/-180, but it goes with the big arc

**Expected behavior**
It should use shortest line between two GPS coords

So we need to optimise the algorithm to find the shortest way in path layer

**Comment by vasturiano** [comment]
@lslzl3000 good find!
Are you able to put together a simple example on codepen or so, that can be used for dev'ing and adjusting the math behind this?

**Comment by lslzl3000** [comment]
@vasturiano a simple demo https://codepen.io/ShuangLiu/pen/zYKQOWB
![Screen Shot 2021-01-22 at 16 58 54](https://user-images.githubusercontent.com/3398981/105469388-1f6ca200-5cd3-11eb-865c-76781c3fbd22.png)
the arc layer works right with shortest way, but the path goes with the big arc

**Comment by vasturiano** [comment]
Thanks for the example @lslzl3000. This has been fixed in the latest version `2.11.2`. 👍
