### ISSUE TITLE
Example doesn't work(hexed-polygons)

### ISSUE THREAD

**Issue by DarkReduX** [vasturiano/three-globe#24]
**Describe the bug**
I tried run example and got this message:
**Uncaught TypeError: Cannot read property 'BufferGeometryUtils' of undefined
    at x (three-globe:20)
    at updateObj (three-globe:20)
    at three-globe:5
    at Array.forEach (<anonymous>)
    at three-globe:5
    at zt (three-globe:5)
    at Vt (three-globe:5)
    at Function.update (three-globe:20)
    at three-globe:2
    at l (three-globe:2)**

**To Reproduce**
1. Go to 'https://vasturiano.github.io/three-globe/example/hexed-polygons/'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/57458347/110984493-42830c00-837c-11eb-9c0c-b0aacd96d792.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome

**Additional context**
I tried use hexed polygons for my project but it doesn't work. I want to use three-globe instead globe.gl because idk how to work with scene in globe.gl and add other objects

**Comment by vasturiano** [comment]
Thanks for the report @DarkReduX. It is now fixed. It was missing a dev dependency which was affecting only the UMD version of the module.
