### ISSUE TITLE
Make GLOBE_RADIUS configurable

### ISSUE THREAD

**Issue by Anuovec** [vasturiano/three-globe#29]
**Is your feature request related to a problem? Please describe.**
I need to change the Earth Radius because I need very precise coordinates for the object around the earth. I do not need it to be 1:1, but with radius 100, the scale is too big and it is making the 3d simulation look inaccurate.

**Describe the solution you'd like**
Add a `GLOBE_RADIUS` option to `ThreeGlobe`.

**Comment by vasturiano** [comment]
@Anuovec you can simply [scale it](https://threejs.org/docs/#api/en/core/Object3D.scale) down to 1:1, or whatever other dimensions you prefer. The threeJs coordinate space is abstract and was never intended to be meaningful in any particular domain.
