### ISSUE TITLE
Examples of HexBin and HexedPolygon does not output data (layer) onto globe surface

### ISSUE THREAD

**Issue by lezan** [vasturiano/three-globe#30]
**Describe the bug**
I am unable to see any data projected on globe surface with HexBin and HexedPolygon examples.
I can only see globe with a texture.

For HexBin example console prints this output:
```
Uncaught TypeError: e is undefined
    update https://unpkg.com/three-globe:20
    o https://unpkg.com/three-globe:2
    l https://unpkg.com/three-globe:2
three-globe:20:7278
    update https://unpkg.com/three-globe:20
    o https://unpkg.com/three-globe:2
    l https://unpkg.com/three-globe:2
```

For HexedPolygon example console prints this output:
```
 Uncaught TypeError: e is undefined
    x https://unpkg.com/three-globe:20
    updateObj https://unpkg.com/three-globe:20
    en https://unpkg.com/three-globe:5
    en https://unpkg.com/three-globe:5
    en https://unpkg.com/three-globe:5
    tn https://unpkg.com/three-globe:5
    update https://unpkg.com/three-globe:20
    o https://unpkg.com/three-globe:2
    l https://unpkg.com/three-globe:2
```

**To Reproduce**
1. Open https://vasturiano.github.io/three-globe/example/hexbin/
2. Open https://vasturiano.github.io/three-globe/example/hexed-polygons/

**Expected behavior**
I expect to see data mapped onto surface.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 88.0.1 (x64)

**Comment by vasturiano** [comment]
Thanks for the report @lezan! This should now be fixed with the latest version (`2.18.3`). 👍
