### ISSUE TITLE
[Feature request] Clickable Labels

### ISSUE THREAD

**Issue by Scaredtodev** [vasturiano/three-globe#31]
I've scanned trough the documentation, but cannot find anything about adding click functionality to a label?

Maybe a solution to create a callback on the rendered labels/dots and create a raycaster functions on it?

**Comment by vasturiano** [comment]
@Scaredtodev that functionality exists in the higher-level component [globe.gl](https://github.com/vasturiano/globe.gl).

**Comment by Scaredtodev** [comment]
@vasturiano Aah thanks, really awesome! didn't knew about the higher-level component

**Comment by antoniohof** [comment]
how to access it?

**Comment by vasturiano** [comment]
@antoniohof there's an `onLabelClick` method available in that module. See [docs](https://github.com/vasturiano/globe.gl#labels-layer).

**Comment by Fullstack-WEB-Blockchain-Developer** [comment]
> @Scaredtodev that functionality exists in the higher-level component [globe.gl](https://github.com/vasturiano/globe.gl).
Hi @vasturiano 
So do I need to migrate three-globe to react-globe.gl to use onclick and hover events?

**Comment by vasturiano** [comment]
@Fullstack-WEB-Blockchain-Developer they're present also on `globe.gl`, no need to use `react-globe.gl` if you're not in a React environment.
