### ISSUE TITLE
three-fatline dependency problem

### ISSUE THREAD

**Issue by edwmurph** [vasturiano/three-globe#4]
When I try to build my static site in prod it fails with this error:
```
5:08:10 PM: failed Building production JavaScript and CSS bundles - 40.636s
5:08:10 PM: error Generating JavaScript bundles failed
5:08:10 PM: Can't resolve 'three-fatLine' in '/opt/build/repo/node_modules/three-globe/dist'
5:08:10 PM: error Generating JavaScript bundles failed
5:08:10 PM: /opt/build/repo/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/opt/build/repo/src/components/globe.js 2c1f6f1bb8d0d5c79d3cffa76a8ca2cf
5:08:10 PM: Unexpected token (1769:35)
5:08:10 PM: |         var stroke = strokeAccessor(path);
5:08:10 PM: |         var useFatLine = stroke !== null && stroke !== undefined;
5:08:10 PM: |         var obj = useFatLine ? new !(function webpackMissingModule() { var e = new Error("Cannot find module 'three-fatLine'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(new !(function webpackMissingModule() { var e = new Error("Cannot find module 'three-fatLine'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())(), new !(function webpackMissingModule() { var e = new Error("Cannot find module 'three-fatLine'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())()) : new THREE$7.Line(new THREE$7.BufferGeometry(), sharedShaderMaterial.clone() // Separate material instance per object to have dedicated uniforms (but shared shaders)
5:08:10 PM: |         );
5:08:10 PM: |         obj.__globeObjType = 'path'; // Add object type
```

I think I narrowed the problem to https://github.com/vasturiano/three-globe/commit/8742ca425750874e020f6e2e43bc941200894d11 because I confirmed that when I use  three-globe v2.3.4 I see this problem but when I use three-globe v2.1.2 the build passes.

Also interestingly I can build the static site locally but it fails to build in Netlify when it's being deployed in prod. I'm not exactly sure what's causing the error but could this repo do without the `three-fatline` dep? If so, since `three-globe` v2.1.2 works fine, I think removing the need for the `three-fatline` dep would be a simple way to resolve this for me.

**Comment by vasturiano** [comment]
Thanks for reporting this @edwmurph. The root cause of this was a case typo in the `three-fatline` import (was `three-fatLine`). This is now fixed, please pull the latest version of the module (`v2.3.6`).
