### ISSUE TITLE
.htmlElementsData() and .htmlElement() causes an uncaught type error - missing definition?

### ISSUE THREAD

**Issue by divljikunic** [vasturiano/three-globe#52]
Using .htmlElementsData() and .htmlElement() causes a "Uncaught TypeError: ...is not a function"

Going to the definition in "three-globe.d.ts", nothing resembling those functions exists there. As per the docs, there are hexes, polygons, custom layers etc. but no html elements.

1. initialize an instance of ThreeGlobe() and try using the .htmlElementsData() or .htmlElement()

**Comment by vasturiano** [comment]
@divljikunic thanks for reaching out. 

The type definitions should be there: https://github.com/vasturiano/three-globe/blob/bc8492286aebc27d6bc875aafb0254e0964f9242/src/index.d.ts#L264-L276

Are you using a recent version of the package?

**Comment by divljikunic** [comment]
I did an 'npm update' and the error is indeed gone! Thank you.
I had installed the package just recently, so it didn't occur to me this could even be an issue.
