### ISSUE TITLE
JSPM Interop Issue

### ISSUE THREAD

**Issue by guybedford** [vasturiano/three-globe#56]
**Describe the bug**

**To Reproduce**
1. Go to https://jspm.org/sandbox#H4sIAAAAAAAAA51YbVPbOBD+fPwKXe5DnDtsJwQ4jiZM0kApPWA6BNq56fSDYiuJgi35JJkQbu6/30q2gvNSpVdm2sSrR8++SevddH6OeaQWGUFTlSZnex37QXB8todQJyUKo2iKhSSqW8vV2D+pmQVFVULO7giOFBoqLBQRnbAQLvcxnJJu7YmSecaFqqGIM0UY8MxprKbdmDzRiPjmYR9RRhXFiS8jnJBuC7R0wsKMzojHC8P6s+/DB0Ifhh9v0CVhRGDFBbpKNT+6wZlZvYipQg9316fglMrkaRhOLDSYySwNKA9/eTi4nf51+fbx/CK7vR8c3Q0GRx+uB9mH689XfDGc/nkff7p9OUk+DtnDvDm7WTTvb971+yK+/STTfh/0+L4xSUaCZgrpGHZr1BiS4szE6B9jTSmUtdNSACI1FYT4k4SPCIhrSzPx0j6WpacVVO8gODgMjsKYShVW5EHK4zwhsK1muP/dL3TKiGdkReUWHZVlAPRULsbhiPOEYOZnnDLlU/0lWUw4c5jp3tg7Do6CZmE4kSFlMXnW5u6va56SJCNC7lRU4r6bl7InLChmaifzEvld3HNC2EyG5lMvutjXsL3WSXAcHJbZNMJoJtc04CgiUnLhj13Br6B6raAdHBSkFXHliFTY47aPhcALB7WF9NpBKzgOpYi2RgJgEU+4cDMZiGFquphikuCc7TLLoiBPTfDYwTfmIsWuzC8xu22bEO4mAgCwNIPWDhb/iQvOON3JZoFw+3ewwp0jAm4cVq6CsgrcbaspxW4+A+kd7sqDoukOIo0wFjlzoFHfldQKEKzbkVklqH418XzHIX7FwV1zeowV9me6EroIlyBgO7DF/VX6jYtLRjxnkTOaJcTQtrYbWNwg5b62S1DvyCRmGxPBIspdbhYA/QIL2iZghWCNZiygV4CsRY/EZVIVZnLQLqL2TsvvjXiNeNr2ncXZrMPB+92WzpHgc0lEaBbWyEwAiqroj1xFahVYrcyrK9tzbC4p022ES0OJMcWh/c2j+IgzmTtvcYkAI1sQhsLKUrbdvExw/XZxvfH0QxhxQYx1TX8E7SB0MCHjcKjoSC6jXHL58BnnkaKcrSkTfJRLBeskphFULZfaDWxZ4rbFxTRRu5qvHuw+BA/CUU6TuGi8tsek6MmgOtDIdj66gkMbLFznxLUNEnIExldavu04l0FjrBLKdjeZJQ78PbJXamXBpQPsmMn/4+76Bn3y7MHbjnCoD8kzTrME2rSZTMNyA4XHe/KsLu1+ZwlYTfX38rkNSTiOoUsN38H74tp8/2EbtlO51QsCR17oXYPh8OD8rnz8YRscfG5DckUTGb7Nx2MibPQetOyHTXEyVo2hbGG6zgOXniUIDuEh1OilYDlSwVC1Z//X/zphMfLpCa+cSdHFEN2YE4qGU5rKUzuRQnmWSN/XMU0SBO0IKg6yRGX9k2hO1ZTnCtHKDpln5sHDsIs8RwQGzMFUgK/o5I/fGmujJ5YLFiGo/91vvoKlX+j1pTavWljWlrTXKBJczw50Qlm3hhlni5Tnsna27vnK6FuwmLkXWWfudRYv9ZyKxmA9qlcm1/qbvb2ffgpDPcYjgVkM67r3Mfuh0EmFblEXtZvNNxXR5BwgIP4SBEFfv0O920bwSBbSa3wNIHae10DdM+TZuRb63FPk3WA1DQodsO4jqHIN9CtqnTTteUnY5Nu49vESJ+kLOUWruBC17bI5OafoSx3eQPV9VJ9PqSL6yyjJzecE/Gf1r18KBujS4jWloK3xtThvjQaE6NX1Io5dxMi8ElivUaoOTFSvUjwhDyLx6mGYs+xxEkQ8rf5gYO9SSNOJ7sTU1I+xeAxm2aS+pBrlafYjTIrDWeeTRZCxCpv5RUDqxHkmfasL/URRlcfEq+vYru0a6Hh6dRPWug2HJOoeunu4NGW2bbINewC37AJHUy/WS3GgWSFqK1FuvCl3mBBuGvim/C0FHTabTasWjuqQqDxDthZWcmNFNj3v7y4ugs9kdHltK6VXklpkAF4MwTRvDs0JnweUMSI+F7+EVUXvCZ1MVbk55lGeEpgMJkRdJER/fbu4ir26Scgn+lJvBDjLQMVgCv2Kt1QGXpf4DW9kRBipuGKeV/wYaom13ywHOI49E7sN6eu2fjqioPBa2+81n0fmr+HYcE4FMR0gTuymsfnbh4t43NiwPIKWX1TrRSFYsf0jlNhMsz6RgVm1fhTYAJtV2LKRhnAzCys78wyqFfko+KwwGg6YoM9r9BmX1PS0L6DiSJcy60I/jq29eqQUPJEVT9RoUApXvLkXOHocwUvBrnoFxT7anmlN+EoVpJSdQ83HMBoCbavZ2kAIrsCpYUZIrA3eWH/hPLWrzeDk1Z0/YfTy+Xi8ejm8MYyh2n+EGYVJHE4R+kfDr67eXZRXEJ7M8IaiRZSQUlhRWcTZW17ZpafFF8+cpP0ylhXU3zmRqm/UggFGhVdaYe93o2B9fa11wuKX5k5Y/Az+H5ipKlgeFwAA
2. See error

**Expected behavior**
three-globe should be supported on JSPM

**Additional context**

JSPM tries to use the module version of three-globe, which in turn imports `frame-ticker` like this:

```js
import FrameTicker from 'frame-ticker';
```

JSPM follows the Node.js CJS / ESM interop pattern (https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#commonjs-namespaces), which therefore treats the default export of a CommonJS module as the CommonJS module itself.

This matches FrameTickers own documentation as to the CommonJS representation of FrameTicker requiring an explicit `.default` access - https://www.npmjs.com/package/frame-ticker#usage.

The correct pattern to use by Node.js interop while also supporting Webpack interop would be:

```js
import _FrameTicker from 'frame-ticker';
const FrameTicker = _FrameTicker.default || FrameTicker;
```

This two line change should be enough to get comprehensive JSPM support.

**Comment by paulbrie** [comment]
https://teleporthq.io is using JSPM and we would really appreciate to allow our users to use Three.js in our platform! ;)

**Comment by guybedford** [comment]
@vasturiano the last publish was 5 years ago so that may be a little ambitious unfortunately...

**Comment by vasturiano** [comment]
Yeah, that's a fair point. Ok, I've made the change, that should unblock you. Let me know if you come across any other interop issues with jspm. 👍
