### ISSUE TITLE
Use in typescript

### ISSUE THREAD

**Issue by hrstrand** [vasturiano/three-globe#7]
I would like to Three-globe  in Typescript, as an import.
Is there a recommended way to do this?

Being a Typescript newbie, I fail to get Typescript to import correctly. I keep ending up with a FromKapsule object, where I expect a ThreeGlobe

**Comment by hrstrand** [comment]
(figured it out)

**Comment by vasturiano** [comment]
@hrstrand fyi, I've just added a TS declarations file to the library: 
https://github.com/vasturiano/three-globe/blob/master/src/index.d.ts

Just pull the latest published version: `2.6.4`.
