### ISSUE TITLE
Bug: FrameTicker doesn't get disposed

### ISSUE THREAD

**Issue by Andrewknackstedt** [vasturiano/three-globe#74]
Follow up of #72.

These three instances of using FrameTicker do not get terminated when the deconstructor is called from globe.gl.
https://github.com/vasturiano/three-globe/blob/0fe579ffda33a5101c541176bb815837023ea749/src/layers/arcs.js#L122
https://github.com/vasturiano/three-globe/blob/de3c481a2c6b509f5d14adec41047777b6a7a72d/src/layers/rings.js#L54
https://github.com/vasturiano/three-globe/blob/de3c481a2c6b509f5d14adec41047777b6a7a72d/src/layers/paths.js#L114

I'd also note that having all of these methods hook into requestAnimationFrame might negatively impact overall performance, though I'm not familiar enough to say if that is avoidable

**Comment by vasturiano** [comment]
Thanks @Andrewknackstedt. I've include the disposal of those other raf consumers to the globe destructor.
