### ISSUE TITLE
"Window is not defined" error when extending on NextJS.

### ISSUE THREAD

**Issue by akchro** [vasturiano/three-globe#86]
**Describe the bug**
To use three-globe on react-three-fiber, I have to use react-three-fiber's extend function to import it. Doing so causes a "window is not defined" error that does not break the dev environment, but restricts next build.

**To Reproduce**
1. Create a NextJS app
2. I a component file, ```import ThreeGlobe from "three-globe";```
3. After importing, ```extend({ThreeGlobe})```

**Expected behavior**
three-globe imported without any errors

**Screenshots**
Error logs:
<img width="1084" alt="image" src="https://github.com/vasturiano/three-globe/assets/75696154/3623c2f9-b0e1-498b-825f-cf480cae03b8">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version: Version 115.0.5790.114 (Official Build) (arm64)

**Smartphone (please complete the following information):**
Not Tested on smartphone

**Additional context**
N/A

**Comment by vasturiano** [comment]
This module is not really compatible with SSR. You probably need to disable it in next.

**Comment by akchro** [comment]
I tried using a dynamic import and also tried "use client". I still get a window not defined error. Any other ways to disable ssr?
